"""Update exercice and set in selectin

Revision ID: 4607b3fb700d
Revises: e3b6ede0199f
Create Date: 2025-09-20 00:55:14.625802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4607b3fb700d'
down_revision: Union[str, Sequence[str], None] = 'e3b6ede0199f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
