"""Readd routine table

Revision ID: 6a68d895940e
Revises: f114de99c500
Create Date: 2025-09-14 23:56:07.646542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a68d895940e'
down_revision: Union[str, Sequence[str], None] = 'f114de99c500'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('routine',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('validated', sa.Boolean(), nullable=False),
    sa.Column('cooldown_days', sa.Integer(), nullable=False),
    sa.Column('last_validation', sa.DateTime(timezone=True), nullable=True),
    sa.Column('strike', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('routine', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_routine_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('routine', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_routine_id'))

    op.drop_table('routine')
    # ### end Alembic commands ###
