"""Update set time to duration

Revision ID: 742061e4427e
Revises: 4607b3fb700d
Create Date: 2025-09-20 10:00:35.784933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '742061e4427e'
down_revision: Union[str, Sequence[str], None] = '4607b3fb700d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('set', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duration', sa.Time(), nullable=True))
        batch_op.drop_column('time')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('set', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time', postgresql.TIME(), autoincrement=False, nullable=True))
        batch_op.drop_column('duration')

    # ### end Alembic commands ###
