"""remove user test

Revision ID: 7d0e8be86077
Revises: be95a57a9c82
Create Date: 2025-09-13 18:47:00.899226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d0e8be86077'
down_revision: Union[str, Sequence[str], None] = 'be95a57a9c82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('user', schema=None) as batch_op:
    #     batch_op.drop_column('sisid')
    pass

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sisid', sa.UUID(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
