"""Add Timer table

Revision ID: 8d093a7d52bc
Revises: ef6552e22b71
Create Date: 2025-09-15 20:33:00.309219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d093a7d52bc'
down_revision: Union[str, Sequence[str], None] = 'ef6552e22b71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('worktime', sa.Time(), nullable=False),
    sa.Column('breaktime', sa.Time(), nullable=False),
    sa.Column('custom', sa.Boolean(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('timer', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_timer_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('timer', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_timer_id'))

    op.drop_table('timer')
    # ### end Alembic commands ###
