"""Add movement table

Revision ID: adf839f3b6f8
Revises: e2ca97283713
Create Date: 2025-09-18 23:16:15.074873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adf839f3b6f8'
down_revision: Union[str, Sequence[str], None] = 'e2ca97283713'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('muscle_group', sa.String(length=256), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('movement', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_movement_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movement', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_movement_id'))

    op.drop_table('movement')
    # ### end Alembic commands ###
