"""patch user test

Revision ID: be95a57a9c82
Revises: 151ea780bc73
Create Date: 2025-09-13 18:46:37.632983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be95a57a9c82'
down_revision: Union[str, Sequence[str], None] = '151ea780bc73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass


