"""Fix name session type

Revision ID: e3b6ede0199f
Revises: 1ab697184c75
Create Date: 2025-09-20 00:51:29.000380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3b6ede0199f'
down_revision: Union[str, Sequence[str], None] = '1ab697184c75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercise', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('exercise_session_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('exercise_movement_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'session', ['session_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'movement', ['movement_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_index(batch_op.f('ix_session_name'))

    with op.batch_alter_table('set', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('set_exercise_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'exercise', ['exercise_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('set', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('set_exercise_id_fkey'), 'exercise', ['exercise_id'], ['id'])

    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_session_name'), ['name'], unique=True)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('exercise', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('exercise_movement_id_fkey'), 'movement', ['movement_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('exercise_session_id_fkey'), 'session', ['session_id'], ['id'])

    # ### end Alembic commands ###
