"""Remove routine table

Revision ID: f114de99c500
Revises: 07785a7ddbf5
Create Date: 2025-09-14 23:45:04.632799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f114de99c500'
down_revision: Union[str, Sequence[str], None] = '07785a7ddbf5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('routine', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_routine_id'))

    op.drop_table('routine')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('routine',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('validated', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('cooldown_days', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('last_validation', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('strike', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('owner_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], name=op.f('routine_owner_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('routine_pkey'))
    )
    with op.batch_alter_table('routine', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_routine_id'), ['id'], unique=False)

    # ### end Alembic commands ###
